- имя: Кэш
  использует: действия/кэш@v3.3.2
  с:
    # Список файлов, каталогов и шаблонов подстановочных знаков для кэширования и восстановления.
    путь:
    # Явный ключ для восстановления и сохранения кеша
    ключ:
    # Упорядоченный список ключей, который будет использоваться для восстановления устаревшего кеша, если для ключа не произошло попадания в кеш. Обратите внимание: в этом случае `cache-hit` возвращает false.
    ключи восстановления: # необязательно
    # Размер фрагмента, используемый для разделения больших файлов во время загрузки, в байтах
    размер загружаемого фрагмента: # необязательно
    # Необязательное логическое значение, если оно включено, позволяет запускающим Windows сохранять или восстанавливать кеши, которые можно восстановить или сохранить соответственно на других платформах.
    EnableCrossOsArchive: # необязательно, по умолчанию — false
    # Сбой рабочего процесса, если запись в кэше не найдена
    fail-on-cache-miss: # необязательно, по умолчанию — false
    # Проверяем, существует ли запись в кеше для заданных входных данных (ключ, ключи восстановления) без загрузки кеша
    только для поиска: # необязательно, по умолчанию — false
